apiVersion: v1
kind: Service
metadata:
  name: task-api
  labels:
    app: task-api
spec:
  type: ClusterIP
  selector:
    app: task-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
